version: 2

sources:
 
  - name: linkedin_ingestion
    database: demo  
    schema: demo_schema      # Matches schema in profiles.yml
    tables:
      - name: linkedin_jobs
      - name: jobs_linkedin_cleaned
  
